target_sources(
  obs-studio
  PRIVATE
    docks/OBSDock.cpp
    docks/OBSDock.hpp
    docks/HimotheeMultistreamDock.cpp
    docks/HimotheeMultistreamDock.hpp
    docks/HimotheeOverlayDock.cpp
    docks/HimotheeOverlayDock.hpp
    overlays/HimotheeOverlayEngine.cpp
    overlays/HimotheeOverlayEngine.hpp
)
